<?php
echo \yii\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => [
        'id',
//        'client_id',
//        'kassa_id',
//        'xodim_id',
//        'seriya',
//        'nomer',
        'sana',
//        'qabul_sana',
        'summa',
        'sum_naqd',
        'sum_plastik',
//        'sum_epos',
//        'cheg_n',
//        'cheg_p',
//        'cheg_e',
//        'sum_naqd_ch',
//        'sum_plast_ch',
//        'sum_epos_ch',
//        'summa_ch',
        'kol',
//        'changedate'
//        'user_id',
//        'del_flag',
//        'tur_oper',
//        'diler_id',
//        'print_flag',
//        'ombor_id',
//        'filial_id',
//        'shartnoma_id',
//        'woywo_bill_type',
        'qarz_summa',
        'qarz_kim',
        'qarz_izoh',
        'qarz_flag',
//        'h_id',
//        'pl_id',
//        'kurs',
//        'dollar',
//        'sum_d',
    ],
])
?>